import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextuiProviderSet from "@/components/provider/nextuiProviderSet";
import AuthCheck from "@/components/provider/authCheck";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Super Time",
  description: "Generated by 2311-Team 01",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextuiProviderSet>
          <AuthCheck />
          {children}
        </NextuiProviderSet>
      </body>
    </html>
  );
}
